# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NBpbhfTxzCA5dgwlaaAY9l6OfZf56PwF
"""

print("the hello World")
